# Example Inventory Data aligned with Merchant Admin example-data.js (inventoryDataExample)
# Converted to Python and used by backend handlers for demo/mock DB

exampleInventoryData = {
    "materials": [
        {
            "merchant_id": 1,
            "material_id": 101,
            "sku": "MAT-101",
            "name": "紅茶茶葉",
            "unit": "g",
            "unit_precision": 2,
            "stock_quantity": 5000.0,
            "min_stock_alert": 500.0,
            "reorder_point": 800.0,
            "reorder_qty": 3000.0,
            "lot_tracking": False,
            "expiry_tracking": False,
            "lead_time_days": 3,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-08-01T10:00:00Z",
        },
        {
            "merchant_id": 1,
            "material_id": 102,
            "sku": "MAT-102",
            "name": "牛奶",
            "unit": "ml",
            "unit_precision": 0,
            "stock_quantity": 20000.0,
            "min_stock_alert": 2000.0,
            "reorder_point": 3000.0,
            "reorder_qty": 10000.0,
            "lot_tracking": False,
            "expiry_tracking": False,
            "lead_time_days": 2,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-08-01T10:00:00Z",
        },
        {
            "merchant_id": 1,
            "material_id": 103,
            "sku": "MAT-103",
            "name": "珍珠",
            "unit": "g",
            "unit_precision": 2,
            "stock_quantity": 3000.0,
            "min_stock_alert": 300.0,
            "reorder_point": 500.0,
            "reorder_qty": 2000.0,
            "lot_tracking": False,
            "expiry_tracking": False,
            "lead_time_days": 5,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-08-01T10:00:00Z",
        },
        {
            "merchant_id": 1,
            "material_id": 104,
            "sku": "MAT-104",
            "name": "椰果",
            "unit": "g",
            "unit_precision": 2,
            "stock_quantity": 1500.0,
            "min_stock_alert": 200.0,
            "reorder_point": 300.0,
            "reorder_qty": 1500.0,
            "lot_tracking": False,
            "expiry_tracking": False,
            "lead_time_days": 4,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-08-01T10:00:00Z",
        },
        {
            "merchant_id": 1,
            "material_id": 105,
            "sku": "MAT-105",
            "name": "蛋糕粉",
            "unit": "g",
            "unit_precision": 2,
            "stock_quantity": 1000.0,
            "min_stock_alert": 100.0,
            "reorder_point": 200.0,
            "reorder_qty": 1000.0,
            "lot_tracking": False,
            "expiry_tracking": False,
            "lead_time_days": 7,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-08-01T10:00:00Z",
        },
        {
            "merchant_id": 1,
            "material_id": 106,
            "sku": "MAT-106",
            "name": "抹茶粉",
            "unit": "g",
            "unit_precision": 2,
            "stock_quantity": 800.0,
            "min_stock_alert": 80.0,
            "reorder_point": 150.0,
            "reorder_qty": 600.0,
            "lot_tracking": False,
            "expiry_tracking": False,
            "lead_time_days": 10,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-08-01T10:00:00Z",
        },
        {
            "merchant_id": 1,
            "material_id": 107,
            "sku": "MAT-107",
            "name": "鮮奶油",
            "unit": "ml",
            "unit_precision": 0,
            "stock_quantity": 3000.0,
            "min_stock_alert": 300.0,
            "reorder_point": 500.0,
            "reorder_qty": 1500.0,
            "lot_tracking": False,
            "expiry_tracking": False,
            "lead_time_days": 2,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-08-01T10:00:00Z",
        },
        {
            "merchant_id": 1,
            "material_id": 108,
            "sku": "MAT-108",
            "name": "巧克力醬",
            "unit": "g",
            "unit_precision": 2,
            "stock_quantity": 1200.0,
            "min_stock_alert": 120.0,
            "reorder_point": 200.0,
            "reorder_qty": 800.0,
            "lot_tracking": False,
            "expiry_tracking": False,
            "lead_time_days": 6,
            "is_active": False,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-08-01T10:00:00Z",
        },
    ],
    "movements": [
        {
            "merchant_id": 1,
            "movement_id": 1,
            "material_id": 101,
            "movement_type": "PURCHASE_RECEIPT",
            "quantity": 5000.0,
            "unit_cost": 80.0,
            "reference_type": "PO",
            "reference_id": "1",
            "batch_no": None,
            "expiry_date": None,
            "note": "首次進貨",
            "created_by": "system",
            "created_at": "2025-07-01T08:00:00Z",
        },
        {
            "merchant_id": 1,
            "movement_id": 2,
            "material_id": 102,
            "movement_type": "PURCHASE_RECEIPT",
            "quantity": 20000.0,
            "unit_cost": 30.0,
            "reference_type": "PO",
            "reference_id": "2",
            "batch_no": None,
            "expiry_date": None,
            "note": "首次進貨",
            "created_by": "system",
            "created_at": "2025-07-01T08:00:00Z",
        },
        {
            "merchant_id": 1,
            "movement_id": 3,
            "material_id": 103,
            "movement_type": "PURCHASE_RECEIPT",
            "quantity": 3000.0,
            "unit_cost": 50.0,
            "reference_type": "PO",
            "reference_id": "3",
            "batch_no": None,
            "expiry_date": None,
            "note": "首次進貨",
            "created_by": "system",
            "created_at": "2025-07-01T08:00:00Z",
        },
        {
            "merchant_id": 1,
            "movement_id": 4,
            "material_id": 104,
            "movement_type": "PURCHASE_RECEIPT",
            "quantity": 1500.0,
            "unit_cost": 40.0,
            "reference_type": "PO",
            "reference_id": "4",
            "batch_no": None,
            "expiry_date": None,
            "note": "首次進貨",
            "created_by": "system",
            "created_at": "2025-07-01T08:00:00Z",
        },
        {
            "merchant_id": 1,
            "movement_id": 5,
            "material_id": 105,
            "movement_type": "PURCHASE_RECEIPT",
            "quantity": 1000.0,
            "unit_cost": 60.0,
            "reference_type": "PO",
            "reference_id": "5",
            "batch_no": None,
            "expiry_date": None,
            "note": "首次進貨",
            "created_by": "system",
            "created_at": "2025-07-01T08:00:00Z",
        },
        {
            "merchant_id": 1,
            "movement_id": 6,
            "material_id": 106,
            "movement_type": "PURCHASE_RECEIPT",
            "quantity": 800.0,
            "unit_cost": 70.0,
            "reference_type": "PO",
            "reference_id": "6",
            "batch_no": None,
            "expiry_date": None,
            "note": "首次進貨",
            "created_by": "system",
            "created_at": "2025-07-01T08:00:00Z",
        },
        {
            "merchant_id": 1,
            "movement_id": 7,
            "material_id": 107,
            "movement_type": "PURCHASE_RECEIPT",
            "quantity": 3000.0,
            "unit_cost": 90.0,
            "reference_type": "PO",
            "reference_id": "7",
            "batch_no": None,
            "expiry_date": None,
            "note": "首次進貨",
            "created_by": "system",
            "created_at": "2025-07-01T08:00:00Z",
        },
        {
            "merchant_id": 1,
            "movement_id": 8,
            "material_id": 108,
            "movement_type": "PURCHASE_RECEIPT",
            "quantity": 1200.0,
            "unit_cost": 100.0,
            "reference_type": "PO",
            "reference_id": "8",
            "batch_no": None,
            "expiry_date": None,
            "note": "首次進貨",
            "created_by": "system",
            "created_at": "2025-07-01T08:00:00Z",
        },
    ],
    "purchase_orders": [
        {
            "merchant_id": 1,
            "purchase_id": 1,
            "supplier_id": 1,
            "supplier_name": "台灣茶葉公司",
            "status": "RECEIVED",
            "expected_date": "2025-07-02",
            "currency": "TWD",
            "totals": {"subtotal": 400000, "tax": 0, "shipping": 0, "discount": 0, "total": 400000},
            "items": [
                {"material_id": 101, "ordered_qty": 5000.0, "received_qty": 5000.0, "price": 80.0}
            ],
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-01T09:00:00Z",
        },
        {
            "merchant_id": 1,
            "purchase_id": 2,
            "supplier_id": 2,
            "supplier_name": "牛奶大王",
            "status": "RECEIVED",
            "expected_date": "2025-07-02",
            "currency": "TWD",
            "totals": {"subtotal": 600000, "tax": 0, "shipping": 0, "discount": 0, "total": 600000},
            "items": [
                {"material_id": 102, "ordered_qty": 20000.0, "received_qty": 20000.0, "price": 30.0}
            ],
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-01T09:00:00Z",
        },
        {
            "merchant_id": 1,
            "purchase_id": 3,
            "supplier_id": 3,
            "supplier_name": "珍珠工坊",
            "status": "RECEIVED",
            "expected_date": "2025-07-02",
            "currency": "TWD",
            "totals": {"subtotal": 150000, "tax": 0, "shipping": 0, "discount": 0, "total": 150000},
            "items": [
                {"material_id": 103, "ordered_qty": 3000.0, "received_qty": 3000.0, "price": 50.0}
            ],
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-01T09:00:00Z",
        },
        {
            "merchant_id": 1,
            "purchase_id": 4,
            "supplier_id": 4,
            "supplier_name": "椰果供應商",
            "status": "RECEIVED",
            "expected_date": "2025-07-02",
            "currency": "TWD",
            "totals": {"subtotal": 60000, "tax": 0, "shipping": 0, "discount": 0, "total": 60000},
            "items": [
                {"material_id": 104, "ordered_qty": 1500.0, "received_qty": 1500.0, "price": 40.0}
            ],
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-01T09:00:00Z",
        },
        {
            "merchant_id": 1,
            "purchase_id": 5,
            "supplier_id": 5,
            "supplier_name": "蛋糕原料商",
            "status": "RECEIVED",
            "expected_date": "2025-07-02",
            "currency": "TWD",
            "totals": {"subtotal": 60000, "tax": 0, "shipping": 0, "discount": 0, "total": 60000},
            "items": [
                {"material_id": 105, "ordered_qty": 1000.0, "received_qty": 1000.0, "price": 60.0}
            ],
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-01T09:00:00Z",
        },
        {
            "merchant_id": 1,
            "purchase_id": 6,
            "supplier_id": 6,
            "supplier_name": "抹茶進口商",
            "status": "RECEIVED",
            "expected_date": "2025-07-02",
            "currency": "TWD",
            "totals": {"subtotal": 56000, "tax": 0, "shipping": 0, "discount": 0, "total": 56000},
            "items": [
                {"material_id": 106, "ordered_qty": 800.0, "received_qty": 800.0, "price": 70.0}
            ],
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-01T09:00:00Z",
        },
        {
            "merchant_id": 1,
            "purchase_id": 7,
            "supplier_id": 7,
            "supplier_name": "鮮奶油供應商",
            "status": "RECEIVED",
            "expected_date": "2025-07-02",
            "currency": "TWD",
            "totals": {"subtotal": 270000, "tax": 0, "shipping": 0, "discount": 0, "total": 270000},
            "items": [
                {"material_id": 107, "ordered_qty": 3000.0, "received_qty": 3000.0, "price": 90.0}
            ],
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-01T09:00:00Z",
        },
        {
            "merchant_id": 1,
            "purchase_id": 8,
            "supplier_id": 8,
            "supplier_name": "巧克力工廠",
            "status": "RECEIVED",
            "expected_date": "2025-07-02",
            "currency": "TWD",
            "totals": {"subtotal": 120000, "tax": 0, "shipping": 0, "discount": 0, "total": 120000},
            "items": [
                {"material_id": 108, "ordered_qty": 1200.0, "received_qty": 1200.0, "price": 100.0}
            ],
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-01T09:00:00Z",
        },
    ],
    "suppliers": [
        {
            "supplier_id": 1,
            "merchant_id": 1,
            "name": "台灣茶葉公司",
            "contact_name": "王小明",
            "phone": "+886-2-1234-5678",
            "email": "sales-tea@example.com",
            "address": "台北市…",
            "lead_time_days": 3,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-15T12:00:00Z",
        },
        {
            "supplier_id": 2,
            "merchant_id": 1,
            "name": "牛奶大王",
            "contact_name": "李小牛",
            "phone": "+886-3-222-0000",
            "email": "milk@example.com",
            "address": "新竹市…",
            "lead_time_days": 2,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-15T12:00:00Z",
        },
        {
            "supplier_id": 3,
            "merchant_id": 1,
            "name": "珍珠工坊",
            "contact_name": "陳阿珠",
            "phone": "+886-4-456-7890",
            "email": "boba@example.com",
            "address": "台中市…",
            "lead_time_days": 5,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-15T12:00:00Z",
        },
        {
            "supplier_id": 4,
            "merchant_id": 1,
            "name": "椰果供應商",
            "contact_name": "張椰果",
            "phone": "+886-7-000-1111",
            "email": "nata@example.com",
            "address": "高雄市…",
            "lead_time_days": 4,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-15T12:00:00Z",
        },
        {
            "supplier_id": 5,
            "merchant_id": 1,
            "name": "蛋糕原料商",
            "contact_name": "黃蛋糕",
            "phone": "+886-2-333-4444",
            "email": "cake@example.com",
            "address": "台北市…",
            "lead_time_days": 7,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-15T12:00:00Z",
        },
        {
            "supplier_id": 6,
            "merchant_id": 1,
            "name": "抹茶進口商",
            "contact_name": "綠抹茶",
            "phone": "+886-2-555-6666",
            "email": "matcha@example.com",
            "address": "台北市…",
            "lead_time_days": 10,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-15T12:00:00Z",
        },
        {
            "supplier_id": 7,
            "merchant_id": 1,
            "name": "鮮奶油供應商",
            "contact_name": "白奶油",
            "phone": "+886-6-123-4567",
            "email": "cream@example.com",
            "address": "台南市…",
            "lead_time_days": 2,
            "is_active": True,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-15T12:00:00Z",
        },
        {
            "supplier_id": 8,
            "merchant_id": 1,
            "name": "巧克力工廠",
            "contact_name": "黑可可",
            "phone": "+886-8-999-8888",
            "email": "choco@example.com",
            "address": "屏東縣…",
            "lead_time_days": 6,
            "is_active": False,
            "created_at": "2025-07-01T08:00:00Z",
            "updated_at": "2025-07-15T12:00:00Z",
        },
    ],
}
