version = 0.1

[default.global.parameters]
stack_name        = "my-ordering-foundation"
region            = "us-east-1"
confirm_changeset = true
capabilities      = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"

[default.deploy.parameters]
image_repositories = []

[dev.deploy.parameters]
s3_bucket           = "my-ordering-dev-sam-artifacts"
parameter_overrides = "AppEnv=dev"
