service: order-service

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-3

functions:
  getOrders:
    handler: handler.get_orders
    events:
      - http:
          path: /orders
          method: get
          cors: true
  getOrder:
    handler: handler.get_order
    events:
      - http:
          path: /orders/{order_id}
          method: get
          cors: true
  createOrder:
    handler: handler.create_order
    events:
      - http:
          path: /orders
          method: post
          cors: true
  updateOrder:
    handler: handler.update_order
    events:
      - http:
          path: /orders/{order_id}
          method: put
          cors: true
  deleteOrder:
    handler: handler.delete_order
    events:
      - http:
          path: /orders/{order_id}
          method: delete
          cors: true